### ISSUE TITLE
Issues with Link Editing - Connected to Video Submission Issue

### ISSUE THREAD

**Issue by zzwagil** [openjusticebaltimore/BPDWatch#10]
Editing news links in officer profiles produces duplicate links with newly edited information with the existing unedited link un-removed. The Jorge O. Bernardez Ruiz profile needs to have the first WBAL link removed.

**Comment by dismantl** [comment]
This is addressed by https://github.com/lucyparsons/OpenOversight/pull/646

**Comment by dismantl** [comment]
Just deleted the first WBAL link.
