### ISSUE TITLE
Race Classification Glitch after Editing General Info

### ISSUE THREAD

**Issue by zzwagil** [openjusticebaltimore/BPDWatch#11]
This is a two-fold issue:

1. As an admin, after clicking the blue edit button on the general information section, the following edit screen shows a race drop down box that defaults to "Black". Whatever the race designation was prior to entering the edit screen is erased and becomes "Black".

2. There are compound race designations from the roster such as "Black or African American", "Asian/Pacific Islander", and "American Indian/Alaska Native" that do not show up as options in that edit screen drop down box from the previous point. We should have the race options directly mirror the ethnicity options from the roster. The exact text for those ethnicity options is:

American Indian/Alaska Native
Asian/Pacific Islander
Black or African American
Hispanic
Not Applicable (Non U.S.)
Not Specified
White

**Comment by dismantl** [comment]
Thanks for flagging this @zzwagil. Here's the race categories from the roster:
- Not Specified
- Asian/Pacific Islander
- Black or African American
- American Indian/Alaska Native
- Hispanic
- Not Applicable (Non-U.S.)
- White

Then here are the race categories from OpenOversight:
- Black
- White
- Asian
- Hispanic
- Native American
- Pacific Islander
- Other
- Not Sure

I'll see if I can customize OO to use the categories from the roster.

**Comment by dismantl** [comment]
Fixed by 1e3e70b7d75604400fac26ec422a57a70d42e2a3
