### ISSUE TITLE
Update BPD ranks

### ISSUE THREAD

**Issue by dismantl** [openjusticebaltimore/BPDWatch#13]
The rank choices in BPD Watch are currently the default for OpenOversight, which don't match BPD. The rank data from the rosters needs to be normalized, and then the site rank options need to be updated so the search-by-rank functionality works.

To normalize the rank data, we should use the "job code" columns from the raw rosters to pull in the canonical job titles/ranks. CS is currently working on this.

**Comment by camille-s** [comment]
I added an R script and CSV output of job codes & titles in the BPD data repo. Let me know if that looks like the right format.

**Comment by camille-s** [comment]
@dismantl Just updated this on the data repo.

**Comment by dismantl** [comment]
Complete as of 88eb3b34fc3e0a05bd7ff3313dbd076a9f658d86. Thanks for your work on this @camille-s!
