### ISSUE TITLE
Automatic Time Assignment in Incident Entry

### ISSUE THREAD

**Issue by zzwagil** [openjusticebaltimore/BPDWatch#14]
When entering an incident into the New Incident edit page, when I leave the Time bar beneath Date blank, upon clicking Submit it automatically assigns a random time to the entry. Going back and editing that out by clicking the X on the right side of that bar clears it out in the Edit window, but again upon submission the time is re-assigned to the incident. 

We need to have no time assigned if time is left blank.

**Comment by dismantl** [comment]
This should be fixed as of 3e089a202cf400430fa300669d69b71ffb984490. @zzwagil can you confirm?
