### ISSUE TITLE
Customize style and branding

### ISSUE THREAD

**Issue by dismantl** [openjusticebaltimore/BPDWatch#2]
It would be ideal to customize the branding and style of the BPD Watch site to differentiate it from upstream OpenOversight, and to give it some local Baltimore flavor 😎 

@jkotting made a fantastic [style guide](https://drive.google.com/open?id=1VvAwvpZ7h-dpKJnCkMpGPEvp2VtcPnZA) for us to use.

This would require modifying the CSS (probably adding a separate style sheet for baltimore) and adding one or more header background images.

**Comment by jkotting** [comment]
Some reasonably sized photos marked for reuse with citations to use as needed for background images:

![1200px-bmore_skyline_inner_harbor](https://user-images.githubusercontent.com/30629863/50058199-dd132700-0142-11e9-88ad-9fabe0eb36ba.jpg)

By Nfutvol - Own work, CC BY-SA 4.0, https://commons.wikimedia.org/w/index.php?curid=3382591

![baltimore-217620_1280](https://user-images.githubusercontent.com/30629863/50058220-1cda0e80-0143-11e9-9360-eb5026ad6d7f.jpg)

(no attribution required on above image)

![baltimore_police_officers_at_camden_yards](https://user-images.githubusercontent.com/30629863/50058237-632f6d80-0143-11e9-8abd-853781d84678.jpg)

GoBlue85 [CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0)], from Wikimedia Commons

![protest-1507137_1280](https://user-images.githubusercontent.com/30629863/50058255-aa1d6300-0143-11e9-9dbb-755b4864ce52.jpg)

(no attribution required)

![baltimore-1483763_1280](https://user-images.githubusercontent.com/30629863/50058267-d3d68a00-0143-11e9-85b8-3b0c78c4165e.jpg)

(no attribution required)

**Comment by jkotting** [comment]
![police-224426_1280](https://user-images.githubusercontent.com/30629863/50058284-113b1780-0144-11e9-8847-42d036775745.jpg)

(no attribution required)

![baltimore-239439_1280](https://user-images.githubusercontent.com/30629863/50058291-24e67e00-0144-11e9-9ee4-2e2f4a2fe95c.jpg)

(no attribution required)

![squad-car-1209719_1280](https://user-images.githubusercontent.com/30629863/50058295-362f8a80-0144-11e9-8acf-91bd49a50e48.jpg)

(no attribution required)

![blue-light-73088_1280](https://user-images.githubusercontent.com/30629863/50058299-47789700-0144-11e9-9a66-dc43efbf137d.jpg)

(no attribution required)

![police-862341_1280](https://user-images.githubusercontent.com/30629863/50058311-5c552a80-0144-11e9-89be-bc2b4130f171.jpg)

(no attribution required)
