### ISSUE TITLE
Issues with Video Submission 

### ISSUE THREAD

**Issue by zzwagil** [openjusticebaltimore/BPDWatch#9]
On the Jorge O. Bernardez Ruiz profile, I edited the description of a video I posted, but instead of the existing description showing up edited, a new duplicate post of the original video was posted with the new description. I clicked the Remove button under the video link that had the wrong description, but that did not work. Currently, three videos are attached to his profile. The second video needs to be removed.

**Comment by dismantl** [comment]
This is addressed by https://github.com/lucyparsons/OpenOversight/pull/646

**Comment by dismantl** [comment]
Just removed the second (duplicate) video.
